name: Build Snap

on:
  workflow_dispatch:
  # push:
  #   branches: [ default ]

jobs:
  sources:
    uses: ./.github/workflows/prep_sources.yml

  build:
    needs: sources
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # checkout directly in build/sources so that
        # sources dirs are aside snap dir
        path: beremiz_public_dist

    - name: Download source artifact
      uses: actions/download-artifact@v3
      with:
        name: source_package
        path: build

    - name: Move snap dir in build/sources
      run: |
        ls -R
        mv beremiz_public_dist/snap build/sources
        ls build/sources

    - name: Invoke snapcraft build
      uses: snapcore/action-build@v1
      id: snapcraft
      with:
        path: build/sources

    - name: Upload built artifact
      uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}


